### ISSUE TITLE
`TapOutputCollector` committing partial output on task failure

### ISSUE THREAD

**Issue by archcosmo** [cwensel/cascading#81]
According to the implementation of `TapOutputCollector#close` and `Hadoop18TapUtil#needsTaskCommit`, work is always committed as long as something exists in the work path. As a result, I am seeing partial output files committed in S3 when I use a `PartitionTap` and my task fails after it has written some output.

Is this expected behaviour? I am seeing this in Cascading 3.1, which I understand is a few years old now, but any information here would be of great help

Thanks

**Comment by cwensel** [comment]
A couple things to note.

The concept of 'commit' is about how/when data written to temporary (the `_temporary` folder) locations are renamed/moved into their permanent locations. But when writing to S3, output is written `direct` and not via a temp folder (because there are no atomic renames in S3). So this operation against S3 is effectively disabled.

`PartitionTap` is a wrapper that creates a new Tap for every new partition it encounters. If there is a high cardinality of partitions, there will be a lot of open `Tap` (and open files). So there is a flushing mechanism. So, during normal use, a `Tap`, representing a partition, will be closed, and all the data written (uploaded to S3). If the partition previously closed arrives again, a new file is opened with a new filename (the ordinal of the new opened file is usually added to the filename). The `PartitionTap` could be used in a way it does not write a unique file, and thus overwrites the old file. See the javadoc and source.

If you are interleaving the current `Flow` output with older output, you could have issues stepping on files as well. There are ways to prevent this, see the javadoc and source.

It would be helpful to know how your task is failing. Also what format are you writing data as, and is it compressed?

Also, Cascading 4.0 is available, and likely has some changes/fixes related to the `PartitionTap`. It just has new maven coordinates. See the README.md.

**Comment by cwensel** [comment]
@archcosmo has this been resolved?

**Comment by cwensel** [comment]
@archcosmo please reopen this if you are still having issues.

**Comment by archcosmo** [comment]
Hi Chris,

Apologies for the delay in getting back to you, this was put on the back burner for a while.

Thank you for your detailed response. Interestingly, I am actually seeing a `_temporary` S3 path being used when a job fails between the time the writer is flushed on `close` and the time that the output is either committed or deleted, so it looks like this commit procedure is still occurring.

I have noticed that if I use a simple `Hfs` tap, the job is aborted in the `LocalJobRunner` when the exception is caught and `abortJob` is called on the `FileOutputCommitter`. The `_temporary` path is present after the writer is flushed, but the partial output is removed from S3 in `FileOutputCommitter::cleanupJob`.

However, when a `ParitionTap` is used, the work is instead committed in `TapOutputCollector`. I still see a `_temporary` path being used after the writer is closed in `TapOutputCollector::close`, but `Hadoop18TapUtil.needsTaskCommit` is returning true, so the output is then committed to the final S3 path despite the fact the job failed.

> `PartitionTap` is a wrapper that creates a new Tap for every new partition it encounters. If there is a high cardinality of partitions, there will be a lot of open `Tap` (and open files). So there is a flushing mechanism. So, during normal use, a `Tap`, representing a partition, will be closed, and all the data written (uploaded to S3). If the partition previously closed arrives again, a new file is opened with a new filename (the ordinal of the new opened file is usually added to the filename).

This makes sense, we are writing the partitions from a reduce task so that each partition is written by one reducer only, so I believe we should avoid this case.

> The `PartitionTap` could be used in a way it does not write a unique file, and thus overwrites the old file. See the javadoc and source.

Not sure I quite follow this. Do you have a specific example to hand, or a reference to the part of the javadoc in question?

> It would be helpful to know how your task is failing. Also what format are you writing data as, and is it compressed?

Currently, I am simulating a task failure while writing by throwing an exception in the sink scheme logic. The data being written is plain text lines, compressed as Gzip.

> Also, Cascading 4.0 is available, and likely has some changes/fixes related to the `PartitionTap`. It just has new maven coordinates. See the README.md.

Thanks, I have also tried this using the Cascading 4.0 library since you replied, and the behaviour is still the same as described above.

---

As the output is being written directly to S3, I am ideally looking for a way to make the `PartitionTap`'s behaviour the same as the `Hfs` tap when it comes to committing or aborting output.

**Comment by archcosmo** [comment]
Hi @cwensel, I don't think I have permission to reopen the issue

**Comment by cwensel** [comment]
Sorry for the delay in responding.

I use `PartitionTap` heavily and would love it to be improved upon. But all the commit magic isn't something I've wanted to touch for years.

If you can get a PR that makes the changes you outlined, I'll happily test it in production on this side as well.

You can decide if you want to make the PR against the 4.0 or 4.5 wips, if 4.0, i'll forward port it, but I won't back port from 4.5 so you can use any Hadoop specific APIs for that version, if any.

**Comment by archcosmo** [comment]
Hi @cwensel, thanks for the reply. This has become less of a priority for us. I don't think I'll have time to get to this, so we can probably just close this issue out for now. If this comes back up for us I will put up the PR you described and reference this issue.

Thanks
